# Generated by Django 4.2.23 on 2025-08-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimation',
            name='field',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
