# Generated by Django 4.2.23 on 2025-08-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirko', '0002_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(default=1, help_text="Enter Font Awesome class e.g. 'fas fa-laptop'", max_length=100),
            preserve_default=False,
        ),
    ]
