# Generated by Django 4.2.23 on 2025-08-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirko', '0003_service_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='icon',
        ),
        migrations.AddField(
            model_name='service',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to='service_icons/'),
        ),
    ]
