# Generated by Django 4.2.23 on 2025-08-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirko', '0004_remove_service_icon_service_icon_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
