# Generated by Django 4.2.23 on 2025-08-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirko', '0005_alter_service_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('features', models.TextField(help_text='Use comma-separated features')),
                ('price', models.CharField(max_length=50)),
            ],
        ),
    ]
